### PR TITLE
Download dependency fixed

### PR DESCRIPTION
**Pull request by vicianm**
The initially provided dependency could not be resolved.

### CODE REVIEW

**Review by hadilq — CHANGES_REQUESTED** [review]
Cannot see your point!! Why should I change the package?!

**Comment by hadilq** [comment]
Close due to inactivity!

**Comment by vicianm** [comment]
Hi, it's just a suggestion I have not investigated in more detail.

In our build.gradle the "com.github.hadilq.liveevent:liveevent:$libVersion" cannot be resolved. So far I'm not sure what causes the issue. However, the "com.github.hadilq:LiveEvent:$libVersion" dependency is resolved immediately.

If I have more info I'll let you know.

**Comment by hadilq** [comment]
Hi! Thank you for your feedback. At some point, I decided to migrate to Sonatype, which you can find it in a19728a4653ade77d6821924ef60ae439f15b10a commit. So if you add `mavenCentral()` in you gradle then it should work.

**Pull request closed without merging**
